kibot:
  version: 1

# Uncomment for 3D blender render (CPU intensive)
# import:
# - file: PCB2Blender_2_1

outputs:
- name: generic_bom_csv
  comment: Generic Bill of Materials in CSV format
  type: bom
  dir: BoM/Generic
  options:
    format: CSV
    count_smd_tht: true

- name: pdf_sch_print
  comment: Schematic in PDF format
  type: pdf_sch_print
  dir: Schematic

- name: gerber
  comment: Gerbers
  type: gerber
  dir: Gerber
  layers: 'all'

- name: basic_step
  comment: 3D model in STEP format
  type: step
  dir: 3D

# Uncomment for 3D blender render (CPU intensive)
# - name: basic_blender_export
#   comment: 3D view from top/30 deg/bottom (Blender)
#   type: blender_export
#   dir: 3D
#   options:
#     pcb3d: _PCB2Blender_2_1
#     outputs:
#     - type: render
#     - type: blender
#     point_of_view:
#     - view: top
#     - rotate_x: 30
#       rotate_z: -20
#       file_id: _30deg
#     - view: bottom
