name: Check C version against TAG version

on:
  workflow_call:
    inputs:
      version:
        description: "The TAG version string for this release"
        required: true
        type: string
      header_file:
        description: "The path to the header file"
        required: false
        type: string
        default: "src/version.h"
      version_define:
        description: "The name of the #define in the header file that contains the version string"
        required: false
        type: string
        default: "VERSION"

jobs:
  c-version:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v6
      - uses: nxlabs-ch/shared-workflows/.github/actions/check-version@main
        with:
          version: ${{ inputs.version }}
          file: ${{ inputs.header_file }}
          extract_cmd: "head -n 10 \"$FILE\" | grep define | grep '${{ inputs.version_define }}' -m 1 | sed 's/\"/ /g' | awk '{print $3}'"
          label: C
