name: Deploy Artifacts to Google Cloud Storage

on:
  workflow_call:
    inputs:
      version:
        description: "The version string for this release"
        required: true
        type: string
      project:
        description: "The project name that will be used as the root folder in the bucket"
        required: true
        type: string
      bucket:
        description: "The GCS bucket where the artifact will be uploaded"
        default: artifacts.nxlabs.ch
        required: false
        type: string
    secrets:
      GCP_PROJECT:
        description: "Google Cloud Project ID"
        required: true
      GCP_CREDENTIALS:
        description: "Credentials for service account"
        required: true
    
jobs:
  deploy-gs:
    runs-on: ubuntu-22.04
    steps:
      - name: Version
        run: echo "${{ inputs.version }}"

      - name: Get all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Zip each artifact again
        run: |
          cd artifacts
          for i in */; do cd "$i" && zip -9 -r "../${i%/}.zip" "." && cd .. && rm -rf "$i" & done; wait
  
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
  
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Upload to Google Cloud Storage
        run: |
          gsutil cp -r artifacts/* \
            gs://${{ inputs.bucket}}/${{ inputs.project}}/${{ inputs.version }}/

