name: Google Cloud Run execute job
on:
  workflow_call:
    inputs:
      job-name:
        description: "Name of the pre-existing job"
        required: true
        type: string
      region:
        description: "The region where to execute the job, defaults to europe-west6"
        default: europe-west6
        required: false
        type: string
    secrets:
      GCP_PROJECT:
        description: "Google Cloud Project ID"
        required: true
      GCP_WORKLOAD_IDENTITY_PROVIDER:
        description: "Workload Identity Provider name"
        required: true

jobs:
  execute:
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'beta'

      - name: Execute Job
        run: |
          gcloud beta run jobs execute ${{ inputs.job-name }} \
            --project ${{ secrets.GCP_PROJECT }} \
            --region ${{ inputs.region }}
