name: Check version in JSON file against TAG version

on:
  workflow_call:
    inputs:
      version:
        description: "The TAG version string for this release"
        required: true
        type: string
      json_file:
        description: "The path and name of the *.json file"
        required: true
        type: string

jobs:
  json-version:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/check-version
        with:
          version: ${{ inputs.version }}
          file: ${{ inputs.json_file }}
          extract_cmd: "head -n 10 \"$FILE\" | grep version -m 1 | sed 's/\"/ /g' | awk '{print $3}'"
          label: JSON
