name: Check kicad schema version against TAG version

on:
  workflow_call:
    inputs:
      version:
        description: "The TAG version string for this release"
        required: true
        type: string
      kicad_sch_path:
        description: "The path to the reference kicad schema file"
        required: true
        type: string

jobs:
  kicad-version:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v6
      - uses: nxlabs-ch/shared-workflows/.github/actions/check-version@main
        with:
          version: ${{ inputs.version }}
          file: ${{ inputs.kicad_sch_path }}
          extract_cmd: "head -n 15 \"$FILE\" | grep rev | sed 's/\"/ /g' | awk '{print $2}'"
          label: KiCad
