name: Check kicad schema version against TAG version

on:
  workflow_call:
    inputs:
      version:
        description: "The TAG version string for this release"
        required: true
        type: string
      kicad_sch_path:
        description: "The path to the reference kicad schema file"
        required: true
        type: string
    
jobs:
    kicad-version:
        runs-on: ubuntu-24.04
        steps:
        - uses: actions/checkout@v4

        - name: Strip v from TAG
          run: |
            TAG=${{ inputs.version }}
            echo "EXPECTED_VERSION=${TAG#v}" >> $GITHUB_ENV

        - name: Get KiCad version from source
          id: kicad-version
          run: |
            echo "schema_version=$(head -15 $KICAD_SCH_PATH | grep rev | sed 's/"/ /g' | awk '{print $2}')" >> $GITHUB_OUTPUT
          env:
            KICAD_SCH_PATH: ${{ inputs.kicad_sch_path }}
        
        - name: Display versions
          run: |
            echo "KiCad schema version: '${{ steps.kicad-version.outputs.schema_version }}'"
            echo "Expected version: '$EXPECTED_VERSION'"

        - name: Check KiCad version
          run: |
            if [[ "${{ steps.kicad-version.outputs.schema_version }}" != "$EXPECTED_VERSION" ]]; then
                echo "KiCad schema version mismatch: ${{ steps.kicad-version.outputs.schema_version }} != $EXPECTED_VERSION"
                if [[ "$EXPECTED_VERSION" == "" ]]; then
                    echo "This is a pre-release version, so this is expected."
                    exit 0
                else
                    echo "This is a release version, so this is unexpected."
                    exit 1
                fi
            fi

