name: Check rust version against TAG version

on:
  workflow_call:
    inputs:
      version:
        description: "The TAG version string for this release"
        required: true
        type: string
      cargo_toml_dir:
        description: "The path to the dir with the Cargo.toml file"
        required: true
        type: string

jobs:
  rust-version:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: nxlabs-ch/shared-workflows/.github/actions/check-version@main
        with:
          version: ${{ inputs.version }}
          file: ${{ inputs.cargo_toml_dir }}/Cargo.toml
          extract_cmd: "head -n 6 \"$FILE\" | grep version -m 1 | sed 's/\"/ /g' | awk '{print $3}'"
          label: Rust
