name: Check version in SPEC file against TAG version

on:
  workflow_call:
    inputs:
      version:
        description: "The TAG version string for this release"
        required: true
        type: string
      spec_file:
        description: "The path and name of the *.spec file"
        required: true
        type: string

jobs:
  spec-version:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: nxlabs-ch/shared-workflows/.github/actions/check-version@main
        with:
          version: ${{ inputs.version }}
          file: ${{ inputs.spec_file }}
          extract_cmd: "tail -n 10 \"$FILE\" | grep version -m 1 | sed \"s/'/ /g\" | sed 's/\"/ /g' | awk '{print $2}'"
          label: SPEC
