name: Check version in YAML file against TAG version

on:
  workflow_call:
    inputs:
      version:
        description: "The TAG version string for this release"
        required: true
        type: string
      yaml_file:
        description: "The path and name of the *.yaml file"
        required: true
        type: string

jobs:
  yaml-version:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v6
      - uses: nxlabs-ch/shared-workflows/.github/actions/check-version@main
        with:
          version: ${{ inputs.version }}
          file: ${{ inputs.yaml_file }}
          extract_cmd: "head -n 10 \"$FILE\" | grep version -m 1 | awk '{print $2}'"
          label: YAML
